### ISSUE TITLE
Proxy can crash on unwrittable stream errors

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#363]
Crashed the service on this error from the logs:

```
Error: Stream is not writable
    at BinaryStream.write (/opt/openrov/socket-proxy/middleware/node_modules/binaryjs/lib/stream.js:84:11)
    at Request._callback (/opt/openrov/socket-proxy/middleware/proxy.js:37:14)
    at Request.self.callback (/opt/openrov/socket-proxy/middleware/node_modules/request/request.js:236:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/opt/openrov/socket-proxy/middleware/node_modules/request/request.js:1142:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/opt/openrov/socket-proxy/middleware/node_modules/request/request.js:1096:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)
```

The tail end of the .log file:

```
Stream requested, url: http://build.openrov.com/debian/dists/v2.5.1-rc1/debian/binary-armhf/Packages.gz
Done
Stream requested, url: http://build.openrov.com/debian/dists/v2.5.1-rc1/debian/i18n/Translation-en.gz
There was an error: null
Status Code: 404
Stream requested, url: http://build.openrov.com/debian/dists/v2.5.1-rc1/debian/i18n/Translation-en.bz2
There was an error: null
Status Code: 404
Stream requested, url: http://build.openrov.com/debian/dists/v2.5.1-rc1/debian/i18n/Translation-en.xz

**Comment by BrianAdams** [comment]
fixed by https://github.com/OpenROV/openrov-proxy/commit/e14c033d3ea59a98282b309dc96f2e18e924750b
