### ISSUE TITLE
Fatal error in notification plugin

### ISSUE THREAD

**Issue by spiderkeys** [OpenROV/openrov-software#573]
From a fresh install on commit https://github.com/OpenROV/openrov-cockpit/commit/04657e62fcd28f56f142a82e0fba3215157957de

Fatal error:
```
Tue, 18 Oct 2016 18:32:52 GMT error:system Error starting plugins: Cannot find module 'Debug'
Tue, 18 Oct 2016 18:32:52 GMT error:system Stack trace: Error: Cannot find module 'Debug'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/spiderkeys/workspace/openrov-cockpit/src/plugins/notifications/index.js:1:91)
```

**Comment by spiderkeys** [comment]
Fixed in: https://github.com/OpenROV/openrov-cockpit/commit/c81bc6ca11109bd65e43d897c691eee0f3b30794
