### ISSUE TITLE
31RC1: Systemdetect appears to be an older version

### ISSUE THREAD

**Issue by BrianAdams** [OpenROV/openrov-software#619]
May have pinned the prior version in the build script

```
Jan 13 20:48:01 openrov systemd[1]: Starting OpenROV System Detection Process...
Jan 13 20:48:34 openrov orov-sysdetect[780]: module.js:471
Jan 13 20:48:34 openrov orov-sysdetect[780]:     throw err;
Jan 13 20:48:34 openrov orov-sysdetect[780]:     ^
Jan 13 20:48:34 openrov orov-sysdetect[780]: Error: Cannot find module 'AppFramework'
Jan 13 20:48:34 openrov orov-sysdetect[780]:     at Function.Module._resolveFilename (module.js:469:15)
Jan 13 20:48:34 openrov orov-sysdetect[780]:     at Function.Module._load (module.js:417:25)
```

**Comment by BrianAdams** [comment]
Fixed tag used to build image: https://github.com/OpenROV-Dev/orov-sysdetect/releases/tag/v31.0.0-release
