### ISSUE TITLE
npm install : Mock

### ISSUE THREAD

**Issue by PRIMETSS** [OpenROV/openrov-software#641]
On both Linux and Windows install
Cloned Repo
NPM version: 
Node version

npm install produces

> 1.1.9 against git://github.com/PolymerElements/iron-a11y-keys-behavior.git#^1.0.0
> font-roboto#1.0.1
> paper-dialog-scrollable#1.1.5
> iron-localstorage#1.0.6
> jquery#3.1.1
> fpsmeter#0.3.1
> jquery-ui#1.12.1
> webcomponentsjs#0.7.24
> i18next#1.11.5
> iron-flex-layout#1.3.7
> eventemitter2#1.0.0
> paper-styles#1.3.1
> paper-dialog-behavior#1.2.9
> polymer#1.11.0
> iron-overlay-behavior#1.10.4
> iron-resizable-behavior#1.0.6
> iron-fit-behavior#1.2.7
> iron-a11y-keys-behavior#1.1.9
> done processing plugin install
> ======== cleaning =======
> /bower_components
> ======== installing =======
> 
> undefined
> No bower.json present
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! OpenROV-Cockpit@31.0.0 install: `node install_lib/bower_install_all.js && node > > > > > > > install_lib/npm_install_all.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the OpenROV-Cockpit@31.0.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Paul.Farrand\AppData\Roaming\npm-cache\_logs\2017-10-20T00_25_07_371Z-> debug.log

Have phython 2.7 and Windows Development Tools installed and fibers is compiling now ok by looks

> D:\DATA\My GitHub\openrov-cockpit\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "" rebuild --release )
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>  fibers.cc
  coroutine.cc
  win_delay_load_hook.cc
..\src\fibers.cc(122): warning C4996: 'v8::String::NewFromOneByte': was declared deprecated [D:\DATA\My GitHub\openrov-cockpit\node_modules\fibers\build\fibers.vcxproj]
  c:\users\paul.farrand\.node-gyp\8.7.0\include\node\v8.h(2672): note: see declaration of 'v8::String::NewFromOneByte'
..\src\fibers.cc(126): warning C4996: 'v8::String::NewFromOneByte': was declared deprecated [D:\DATA\My GitHub\openrov-cockpit\node_modules\fibers\build\fibers.vcxproj]
  c:\users\paul.farrand\.node-gyp\8.7.0\include\node\v8.h(2672): note: see declaration of 'v8::String::NewFromOneByte'
> .....
>      Creating library D:\DATA\My GitHub\openrov-cockpit\node_modules\fibers\build\Release\fibers.lib and object D:\DATA\My GitHub\openrov-cockpit\node_modules\fibers\build\Release\fibers.exp
  Generating code
  Finished generating code
  fibers.vcxproj -> D:\DATA\My GitHub\openrov-cockpit\node_modules\fibers\build\Release\\fibers.node
  fibers.vcxproj -> D:\DATA\My GitHub\openrov-cockpit\node_modules\fibers\build\Release\fibers.pdb (Full PDB)
Installed in `D:\DATA\My GitHub\openrov-cockpit\node_modules\fibers\bin\win32-x64-57\fibers.node`

But stops at

> polymer#1.11.0
iron-overlay-behavior#1.10.4
iron-resizable-behavior#1.0.6
iron-fit-behavior#1.2.7
iron-a11y-keys-behavior#1.1.9
done processing plugin install
======== cleaning =======
/bower_components
======== installing =======

> undefined
No bower.json present
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! OpenROV-Cockpit@31.0.0 install: `node install_lib/bower_install_all.js && node install_lib/npm_install_all.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the OpenROV-Cockpit@31.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

> npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Paul.Farrand\AppData\Roaming\npm-cache\_logs\2017-10-20T00_25_07_371Z-debug.log

npm log shows 

> 1266 verbose lifecycle OpenROV-Cockpit@31.0.0 install: CWD: D:\DATA\My GitHub\openrov-cockpit
1267 silly lifecycle OpenROV-Cockpit@31.0.0 install: Args: [ '/d /s /c',
1267 silly lifecycle   'node install_lib/bower_install_all.js && node install_lib/npm_install_all.js' ]
1268 silly lifecycle OpenROV-Cockpit@31.0.0 install: Returned: code: 1  signal: null
1269 info lifecycle OpenROV-Cockpit@31.0.0 install: Failed to exec install script
1270 verbose stack Error: OpenROV-Cockpit@31.0.0 install: `node install_lib/bower_install_all.js && node install_lib/npm_install_all.js`
1270 verbose stack Exit status 1
1270 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
1270 verbose stack     at emitTwo (events.js:125:13)
1270 verbose stack     at EventEmitter.emit (events.js:213:7)
1270 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1270 verbose stack     at emitTwo (events.js:125:13)
1270 verbose stack     at ChildProcess.emit (events.js:213:7)
1270 verbose stack     at maybeClose (internal/child_process.js:927:16)
1270 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
1271 verbose pkgid OpenROV-Cockpit@31.0.0
1272 verbose cwd D:\DATA\My GitHub\openrov-cockpit
1273 verbose Windows_NT 10.0.15063
1274 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
1275 verbose node v8.7.0
1276 verbose npm  v5.4.2
1277 error code ELIFECYCLE
1278 error errno 1
1279 error OpenROV-Cockpit@31.0.0 install: `node install_lib/bower_install_all.js && node install_lib/npm_install_all.js`
1279 error Exit status 1
1280 error Failed at the OpenROV-Cockpit@31.0.0 install script.
1280 error This is probably not a problem with npm. There is likely additional logging output above.
1281 verbose exit [ 1, true ]

Im struggling to interpret these npm debug logs to gain much useful info to try and work out whats failing.
Any clues?
[2017-10-20T00_25_07_371Z-debug.log](https://github.com/OpenROV/openrov-software/files/1400461/2017-10-20T00_25_07_371Z-debug.log)

**Comment by PRIMETSS** [comment]
npm debug

USE_MOCK=true MOCK_HARDWARE=TRUE PLATFORM=raspberrypi MOCK_VIDEO_TYPE=MJPEG LOG_LEVEL=debug configfile='/tmp/rovconfig.json' pluginsDownloadDirectory='/tmp/plugins' node src/cockpit.js > cock.log

**Comment by PRIMETSS** [comment]
Can now get the web server going and can browse to localhost:8080.
But just get "Preparing to dive" screen and stops there.

Node out put says '

SystemGreeting plugin loaded
MOCK: verifyVersionHandler
MOCK: completeHandler
